version: '3'
services:
  redis:
    image: redis:latest
    restart: always
  auth_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: password
  server:
    build: .
    restart: always
    environment:
      HASH: SUPPPPPPWORLDS
      SALT_ROUNDS: 10
    ports:
      - 3000:5000
